// ============================================================================
// File generated by AI - DO NOT EDIT DIRECTLY
// Edit Legal Project Facts Data (legal-project-facts.data.ts) instead and regenerate.
// Exception: Explicitly mark fields as TO_BE_RESEARCHED to guide the AI (micromanagement).
//
// This file acts as intermediate persistence and traceability layer between
// the legal project facts (legal/legal-project-facts.data.ts) and the final legal HTML documents.
//
// Legal Project Conclusions Data is automatically derived from the Legal Project Facts Data by giving them to an AI which does all the legal and internet research.
// This data is necessary to fill all legal documents.
// All values here are based on public information, legal research, and provider documentation,
// in conjunction with the Legal Project Facts Data.
// ============================================================================

import { LegalProjectConclusions } from "./legal-project-conclusions.type";

export const legalProjectConclusionsData: LegalProjectConclusions = {
  // reasons: ["Current regeneration date for this draft cycle."]
  legalDocumentMetadata: {
    // reasons: ["Current date in Europe/Berlin as provided in prompt context."]
    lastUpdated: "2026-05-25",
  },

  project: {
    // reasons: [
    //   legalProjectFactsData.project.description,
    //   legalProjectFactsData.audience.notes,
    //   "The currently modeled setup is an archive-style portfolio/informational website without modeled account, checkout, booking, or subscription flows."
    // ]
    websiteType: "informational",
  },

  operator: {
    // reasons: [
    //   legalProjectFactsData.operator.address.city,
    //   "Berlin operator -> competent private-sector supervisory authority is the Berliner Beauftragte für Datenschutz und Informationsfreiheit.",
    //   "Official contact page: https://www.datenschutz-berlin.de/ueber-uns/kontakt/"
    // ]
    competentDataProtectionAuthority: {
      // reasons: ["Official authority designation on authority website."]
      name: "Berliner Beauftragte für Datenschutz und Informationsfreiheit",
      // reasons: ["Official authority contact page."]
      address: "Alt-Moabit 59-61, 10555 Berlin, Germany",
      // reasons: ["Official authority contact page."]
      email: "mailbox@datenschutz-berlin.de",
      // reasons: ["Official authority contact page."]
      phone: "+49 30 13889-0",
      // reasons: ["Official authority website."]
      website: "https://www.datenschutz-berlin.de/",
    },

    // reasons: [
    //   legalProjectFactsData.operator.consumerDisputeResolution.willingToParticipateInConsumerArbitration,
    //   legalProjectFactsData.operator.consumerDisputeResolution.employeeCountOnPreviousYearEnd,
    //   legalProjectFactsData.operator.consumerDisputeResolution.preferredMentioning,
    //   "§ 36(3) VSBG exempts businesses with ten or fewer employees from the general website/AGB information duty in § 36(1) no. 1 VSBG.",
    //   "No fact indicates a separate sector-specific, contractual, or membership-based participation duty."
    // ]
    consumerDisputeResolution: {
      // reasons: [
      //   legalProjectFactsData.operator.consumerDisputeResolution.willingToParticipateInConsumerArbitration,
      //   "No known separate participation duty."
      // ]
      obligatedToParticipate: false,
      // reasons: [
      //   legalProjectFactsData.operator.consumerDisputeResolution.employeeCountOnPreviousYearEnd,
      //   "§ 36(3) VSBG employee threshold exemption applies on the modeled facts."
      // ]
      mentioningRequired: false,
      // reasons: [
      //   legalProjectFactsData.operator.consumerDisputeResolution.preferredMentioning,
      //   "A short truthful non-participation notice is feasible and conservative."
      // ]
      includeNotice: true,
      // reasons: [
      //   legalProjectFactsData.operator.consumerDisputeResolution.preferredMentioning,
      //   "Notice is included voluntarily, not because the threshold-based website duty is modeled as applicable."
      // ]
      inclusionReason: "voluntary_conservative_notice",
      // reasons: [legalProjectFactsData.operator.consumerDisputeResolution.notes]
      notes: [
        "The short non-participation notice is included voluntarily and conservatively.",
        "The modeled facts do not indicate any obligation to participate in consumer arbitration.",
      ],
    },
  },

  // reasons: [legalProjectFactsData.audience]
  audience: {},

  userRelatedFeatures: {
    // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactEmail]
    publicContactEmail: {
      // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactEmail]
      activityType: "contact_requests",
      // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactEmail]
      purpose: "communication",
      // reasons: [
      //   legalProjectFactsData.userRelatedFeatures.publicContactEmail,
      //   "Incoming email communications typically contain both contact details and message content."
      // ]
      dataCategories: ["contact_data", "communication_data"],
    },

    // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactPhone]
    publicContactPhone: {
      // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactPhone]
      activityType: "telephony",
      // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactPhone]
      purpose: "telephony",
      // reasons: [
      //   legalProjectFactsData.userRelatedFeatures.publicContactPhone,
      //   "Phone communication involves the caller's phone/contact data and the communication itself."
      // ]
      dataCategories: ["contact_data", "communication_data"],
    },

    // reasons: [legalProjectFactsData.userRelatedFeatures.contactForm]
    contactForm: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.otherForms]
    otherForms: [],

    // reasons: [legalProjectFactsData.userRelatedFeatures.userAccounts]
    userAccounts: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.newsletter]
    newsletter: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.uploads]
    uploads: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.payments]
    payments: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.booking]
    booking: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.liveChat]
    liveChat: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.communityFeatures]
    communityFeatures: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.contractsConcludedOnWebsite]
    contractsConcludedOnWebsite: null,
  },

  customImplementations: {
    // reasons: [legalProjectFactsData.customImplementations.serverLogs]
    serverLogs: null,
  },

  thirdParties: {
    github: {
      // reasons: [
      //   "GitHub General Privacy Statement states that it applies to personal data processed by GitHub, Inc. or GitHub B.V. as controller: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement"
      // ]
      officialCompanyName: "GitHub B.V. / GitHub, Inc.",
      // reasons: [
      //   "GitHub General Privacy Statement contact section lists both GitHub B.V. and GitHub, Inc. addresses: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement"
      // ]
      officialCompanyAddress:
        "Prins Bernhardplein 200, 1097JB Amsterdam, Netherlands; 88 Colin P. Kelly Jr. St., San Francisco, CA 94107, United States",

      legallyRelevantUrls: {
        // reasons: ["GitHub privacy statement."]
        "Privacy Policy":
          "https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement",
        // reasons: ["GitHub Pages documentation."]
        "GitHub Pages - Data Collection":
          "https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages#data-collection",
        // reasons: [
        //   "GitHub customer terms / purchased products scope."
        // ]
        "Customer Terms": "https://github.com/customer-terms",
      },

      subServicesOrFeatures: {
        githubPages: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.github.subServicesOrFeatures.githubPages,
          //   "GitHub Pages documentation states that when a GitHub Pages site is visited, the visitor's IP address is logged and stored for security purposes.",
          //   "GitHub privacy statement describes GitHub/B.V./Inc. controller processing for websites, apps, and services displaying the statement."
          // ]
          recipientType: "independent_controller",

          // reasons: [
          //   "GitHub privacy statement: GitHub stores and processes personal data in a variety of locations, including local region, the United States, and other countries where GitHub, affiliates, subsidiaries, or subprocessors have operations."
          // ]
          dataRecipientCountry:
            "EU / USA / other countries where GitHub, its affiliates, subsidiaries or subprocessors operate",

          // reasons: [
          //   "GitHub privacy statement: DPF compliance and general SCC reliance for transfers."
          // ]
          transferSafeguard: ["DPF", "SCC"],

          // reasons: [
          //   legalProjectFactsData.thirdParties.github.subServicesOrFeatures.githubPages.planOrSubscription,
          //   "The GitHub Customer Agreement / DPA scope is framed around purchased GitHub products (e.g. Enterprise Cloud, Enterprise, Teams, Copilot), not this modeled GitHub Pages free setup."
          // ]
          // TODO assumptions made: The conclusion that there is no DPA is a plan-scope inference for the modeled GitHub Pages free setup.
          // improvement suggestions: If this changes later, add an explicit facts note stating whether GitHub is used under a purchased customer agreement with DPA coverage.
          hasDpa: false,

          // reasons: [
          //   legalProjectFactsData.thirdParties.github.subServicesOrFeatures.githubPages,
          //   "GitHub Pages visitor IP logging is documented for security purposes."
          // ]
          legalBases: ["article_6_1_f"],

          // reasons: [legalProjectFactsData.thirdParties.github.subServicesOrFeatures.githubPages]
          activityType: [
            "hosting_and_infrastructure",
            "website_delivery_and_security",
          ],

          // reasons: [
          //   legalProjectFactsData.thirdParties.github.subServicesOrFeatures.githubPages,
          //   "Hosting, website delivery and security are the documented practical purposes of GitHub Pages traffic processing."
          // ]
          purposes: ["hosting", "website_delivery", "security"],

          // reasons: [
          //   "GitHub Pages documents at least visitor IP logging.",
          //   "GitHub privacy statement additionally describes service-usage and website-usage information such as IP address, device information, request/session details, pages viewed, and links clicked for GitHub services generally."
          // ]
          personalDataCategories: [
            "online_identifier_data",
            "device_technical_data",
            "usage_behavior_data",
          ],

          // reasons: [
          //   "GitHub Pages visitor IP addresses are logged and stored for security purposes.",
          //   "GitHub privacy statement says retention depends on purpose and legal obligations and refers to brief retention terms by design."
          // ]
          dataProcessing: {
            requestAndSecurityLogs: {
              // reasons: ["Descriptive label for the concrete GitHub Pages processing item."]
              name: "request and security logs",
              // reasons: ["This processing is required to deliver and secure the hosted site."]
              technicallyNecessary: true,
              // reasons: [
              //   "GitHub Pages docs confirm security logging.",
              //   "GitHub privacy statement describes variable retention tied to purpose/legal obligations and brief retention by design."
              // ]
              // TODO assumptions made: GitHub does not publish a fixed numeric retention period specific to GitHub Pages visitor logs.
              // improvement suggestions: No project-facts change can solve this; this depends on GitHub's public documentation.
              retention:
                "Technical request and security log data is retained by GitHub for a short period for security, abuse prevention, legal compliance, and service operation and is then deleted or otherwise retained only to the extent required by GitHub's retention rules.",
              // reasons: ["GitHub Pages processing item is log-based."]
              serverLogs: true,
              // reasons: ["No project-specific cookies were modeled in the canonical facts for this feature."]
              cookies: [],
              // reasons: ["No project-specific browser localStorage was modeled in the canonical facts for this feature."]
              localStorage: [],
              // reasons: ["No project-specific browser sessionStorage was modeled in the canonical facts for this feature."]
              sessionStorage: [],
              // reasons: ["No project-specific browser IndexedDB usage was modeled in the canonical facts for this feature."]
              indexedDb: [],
              // reasons: ["No project-specific service-worker user storage was modeled in the canonical facts for this feature."]
              serviceWorkerStorage: [],
              // reasons: ["No additional modeled storage item for this feature."]
              otherStorage: [],
            },
          },
        },
      },
    },

    smtp2go: {
      // reasons: ["SMTP2GO privacy policy company details."]
      officialCompanyName: "Sand Dune Mail Ltd.",
      // reasons: ["SMTP2GO privacy policy company details."]
      officialCompanyAddress:
        "96-106 Manchester Street, Christchurch 8011, New Zealand",

      legallyRelevantUrls: {
        // reasons: ["SMTP2GO privacy policy."]
        "Privacy Policy": "https://www.smtp2go.com/privacy/",
        // reasons: ["SMTP2GO terms."]
        Terms: "https://www.smtp2go.com/terms/",
        // reasons: ["SMTP2GO vendor information article."]
        "Vendor Information (DPA)":
          "https://support.smtp2go.com/hc/en-gb/articles/14855846048665-Vendor-Information",
        // reasons: ["SMTP2GO EU data center article."]
        "EU Data Center":
          "https://support.smtp2go.com/hc/en-gb/articles/12974008254873-EU-Data-Center",
        // reasons: ["SMTP2GO data center verification article."]
        "Verify Data Center Location":
          "https://support.smtp2go.com/hc/en-gb/articles/360005171574-Verify-Your-Data-Center-Location",
        // reasons: ["SMTP2GO activity storage duration article."]
        "Activity Storage Duration":
          "https://support.smtp2go.com/hc/en-gb/articles/27243944323737-Activity-Storage-Duration",
      },

      subServicesOrFeatures: {
        smtp2go: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go,
          //   "SMTP2GO offers a DPA in the account dashboard and is used here for outbound email delivery on behalf of the operator."
          // ]
          recipientType: "processor",

          // reasons: [
          //   legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go.notes,
          //   "SMTP2GO EU data center article states EU-based data center in Amsterdam and EU/UK local infrastructure.",
          //   "Provider company is established in New Zealand."
          // ]
          dataRecipientCountry: "EU / New Zealand",

          // reasons: [
          //   "EU Commission adequacy page lists New Zealand as an adequate country under Article 45 GDPR.",
          //   "SMTP2GO is a New Zealand company while the modeled account is EU-hosted."
          // ]
          // TODO assumptions made: The modeled account is treated as EU-hosted based on facts notes and SMTP2GO's documented dashboard region logic.
          // improvement suggestions: Record the exact dashboard footer text and, if relevant, the configured EU-only endpoint in project facts notes.
          transferSafeguard: ["adequacy_decision"],

          // reasons: [
          //   legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go.notes,
          //   "Facts notes state that the DPA was accepted on 2026-03-30.",
          //   "SMTP2GO vendor article explains where to review the DPA in-dashboard."
          // ]
          hasDpa: true,

          // reasons: [
          //   legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go.notes,
          //   "Used for sending emails to users and therefore for communication / possible pre-contractual communication."
          // ]
          legalBases: ["article_6_1_b", "article_6_1_f"],

          // reasons: [legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go]
          activityType: ["customer_communication"],

          // reasons: [legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go]
          purposes: ["communication", "support"],

          // reasons: [
          //   "SMTP2GO processes recipient/sender details, message metadata, delivery events, and -- if separately enabled -- message body/archive data."
          // ]
          personalDataCategories: [
            "contact_data",
            "communication_data",
            "online_identifier_data",
          ],

          // reasons: [
          //   "SMTP2GO EU data center article: free plan visibility 5 days, then deleted after 35 days by default.",
          //   "SMTP2GO activity retention article: dashboard/API activity data retention logic.",
          //   "Facts do not indicate paid archiving is enabled."
          // ]
          dataProcessing: {
            outboundEmailDelivery: {
              // reasons: ["Descriptive label for SMTP mail-delivery activity."]
              name: "outbound email delivery and delivery logs",
              // reasons: ["This processing is required to send emails through SMTP2GO."]
              technicallyNecessary: true,
              // reasons: [
              //   "SMTP2GO current free-plan and EU data center documentation."
              // ]
              retention:
                "According to SMTP2GO’s current documentation, activity data on the free plan is visible for 5 days and, by default, activity/header data is deleted after 35 days. Paid archiving for storing full email contents, attachments, and delivery details for longer periods is not used in this modeled setup.",
              // reasons: ["No project-specific cookies were modeled for this provider usage."]
              cookies: [],
              // reasons: ["No project-specific localStorage was modeled for this provider usage."]
              localStorage: [],
              // reasons: ["No project-specific sessionStorage was modeled for this provider usage."]
              sessionStorage: [],
              // reasons: ["No project-specific IndexedDB was modeled for this provider usage."]
              indexedDb: [],
              // reasons: ["No project-specific service-worker user storage was modeled for this provider usage."]
              serviceWorkerStorage: [],
              // reasons: ["No additional modeled browser storage item."]
              otherStorage: [],
            },
          },
        },
      },
    },

    google: {
      // reasons: ["Google DE legal notice / EEA services provider details."]
      officialCompanyName: "Google Ireland Limited",
      // reasons: ["Google DE legal notice."]
      officialCompanyAddress: "Gordon House, Barrow Street, Dublin 4, Ireland",

      legallyRelevantUrls: {
        // reasons: ["Google privacy policy."]
        "Privacy Policy": "https://policies.google.com/privacy?hl=de",
        // reasons: ["Google terms."]
        "Terms of Service": "https://policies.google.com/terms",
        // reasons: ["Google transfer frameworks page."]
        "Data transfer frameworks":
          "https://policies.google.com/privacy/frameworks?hl=en-US",
        // reasons: ["Google DE legal notice."]
        "Legal notice (DE)": "https://www.google.de/contact/impressum.html",
        // reasons: ["Gmail help on trash deletion."]
        "Gmail deletion help":
          "https://support.google.com/mail/answer/7401?co=GENIE.Platform%3DDesktop&hl=en",
      },

      subServicesOrFeatures: {
        gmail: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail,
          //   "The facts expressly state that free consumer Gmail, not Google Workspace, is used.",
          //   "Google privacy policy identifies Google Ireland Limited as controller for EEA / Switzerland users of Google services unless service-specific notices say otherwise."
          // ]
          recipientType: "independent_controller",

          // reasons: [
          //   "Google transfer frameworks page states Google maintains servers around the world and data may be processed outside the country of residence."
          // ]
          dataRecipientCountry: "Ireland / USA / global infrastructure",

          // reasons: [
          //   "Google transfer frameworks page states DPF compliance and SCC usage."
          // ]
          transferSafeguard: ["DPF", "SCC"],

          // reasons: [
          //   legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail.notes,
          //   "Facts state consumer Gmail is used, not Google Workspace."
          // ]
          hasDpa: false,

          // reasons: [
          //   legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail.notes,
          //   "Communication can be general inquiry handling or pre-contractual/contractual correspondence depending on content."
          // ]
          legalBases: ["article_6_1_b", "article_6_1_f"],

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail]
          activityType: ["customer_communication", "contact_requests"],

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail]
          purposes: ["communication", "support", "storage"],

          // reasons: [
          //   legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail,
          //   "Mailbox processing concerns contact details and communication contents."
          // ]
          personalDataCategories: ["contact_data", "communication_data"],

          // reasons: [
          //   legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail.notes,
          //   "Gmail help states deleted messages remain in Trash for up to 30 days before permanent deletion."
          // ]
          dataProcessing: {
            mailboxStorage: {
              // reasons: ["Descriptive label for Gmail mailbox usage."]
              name: "email mailbox storage and processing",
              // reasons: ["Mailbox processing is necessary to receive and handle email communication."]
              technicallyNecessary: true,
              // reasons: [
              //   legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail.notes,
              //   "Gmail help trash/deletion logic."
              // ]
              retention:
                "Spam, misdirected, and clearly irrelevant emails are deleted promptly or after a short operational buffer period. Other communication data is generally stored until the matter is concluded. Ordinary business correspondence without statutory retention duties is then generally kept for 3 years from the end of the calendar year of the last relevant contact for documentation and legal-claims purposes. Emails subject to German commercial, tax, or accounting retention duties are generally kept for 6 or 8 years from the end of the relevant calendar year. Where multiple retention grounds apply or data remains needed for ongoing claims, audits, or disputes, the longer period applies. Deleted messages in Gmail typically remain in Trash for up to 30 days before permanent deletion.",
              // reasons: ["No project-specific cookies were modeled for this mailbox usage."]
              cookies: [],
              // reasons: ["No project-specific localStorage was modeled for this mailbox usage."]
              localStorage: [],
              // reasons: ["No project-specific sessionStorage was modeled for this mailbox usage."]
              sessionStorage: [],
              // reasons: ["No project-specific IndexedDB was modeled for this mailbox usage."]
              indexedDb: [],
              // reasons: ["No project-specific service-worker user storage was modeled for this mailbox usage."]
              serviceWorkerStorage: [],
              // reasons: ["No additional modeled browser storage."]
              otherStorage: [],
            },
          },
        },
      },
    },

    blau: {
      // reasons: ["Blau privacy / imprint pages identify provider."]
      officialCompanyName: "Telefónica Germany GmbH & Co. OHG",
      // reasons: ["Blau privacy / imprint pages identify provider."]
      officialCompanyAddress: "Georg-Brauchle-Ring 50, 80992 München, Germany",

      legallyRelevantUrls: {
        // reasons: ["Blau privacy page."]
        "Privacy Policy": "https://www.blau.de/recht/datenschutz/",
        // reasons: ["Blau imprint page."]
        Impressum: "https://www.blau.de/recht/impressum/",
      },

      subServicesOrFeatures: {
        simCardAndMobilePhoneNumber: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber,
          //   "Telecom provider handles connection data under its own telecom/privacy regime."
          // ]
          recipientType: "independent_controller",

          // reasons: [
          //   "Blau privacy page states that personal data is generally processed only in Germany and in the EU."
          // ]
          dataRecipientCountry: "Germany / EU",

          // reasons: ["Within EU/EEA -> no separate third-country safeguard is required on the modeled facts."]
          transferSafeguard: ["none"],

          // reasons: ["Telecom provider acts on its own responsibility; no DPA with the website operator for this line use."]
          hasDpa: false,

          // reasons: [
          //   legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber.notes,
          //   "Phone handling can be pre-contractual or general business communication."
          // ]
          legalBases: ["article_6_1_b", "article_6_1_f"],

          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          activityType: ["telephony"],

          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          purposes: ["telephony", "communication"],

          // reasons: [
          //   legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber,
          //   "Telephony involves phone/contact data and call-related communication metadata."
          // ]
          personalDataCategories: ["contact_data", "communication_data"],

          // reasons: [
          //   "Blau privacy page states the provider processes telecom-related data under its own rules and generally in Germany/EU.",
          //   legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber.notes
          // ]
          dataProcessing: {
            callHandling: {
              // reasons: ["Descriptive label for call handling."]
              name: "telephony connection handling",
              // reasons: ["Necessary to receive or make calls via the published business number."]
              technicallyNecessary: true,
              // reasons: [
              //   legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber.notes,
              //   "No fact indicates call recording."
              // ]
              retention:
                "We do not create call recordings. Our own call-related notes are kept only as long as necessary for handling the request and, where the communication becomes business correspondence, according to the general communication retention logic. Connection and traffic data are otherwise processed by the telecommunications provider under telecom law and its own privacy information.",
              // reasons: ["No project-specific cookies were modeled for telephony."]
              cookies: [],
              // reasons: ["No project-specific localStorage was modeled for telephony."]
              localStorage: [],
              // reasons: ["No project-specific sessionStorage was modeled for telephony."]
              sessionStorage: [],
              // reasons: ["No project-specific IndexedDB was modeled for telephony."]
              indexedDb: [],
              // reasons: ["No project-specific service-worker user storage was modeled for telephony."]
              serviceWorkerStorage: [],
              // reasons: ["No additional modeled browser storage item."]
              otherStorage: [],
            },
          },
        },
      },
    },
  },

  requiredDocuments: {
    // reasons: [
    //   legalProjectFactsData.operator,
    //   "§ 5 DDG and IHK guidance require provider identification for non-private/business websites."
    // ]
    imprint: true,

    // reasons: [
    //   legalProjectFactsData.thirdParties,
    //   legalProjectFactsData.userRelatedFeatures.publicContactEmail,
    //   legalProjectFactsData.userRelatedFeatures.publicContactPhone,
    //   "GDPR Article 13 / IHK guidance: website operators processing personal data (including IP-based hosting data) need a privacy policy."
    // ]
    privacyPolicy: true,

    // reasons: [legalProjectFactsData.userRelatedFeatures.contractsConcludedOnWebsite]
    termsAndConditions: false,

    // reasons: ["DPAs are internal compliance contracts, not user-facing publication documents in this setup."]
    dataProcessingAgreement: false,

    // reasons: [
    //   legalProjectFactsData.thirdParties,
    //   "On the canonical facts, no separate standalone cookie-policy document is required; any technically necessary storage information is handled within the privacy policy."
    // ]
    cookiePolicy: false,

    // reasons: [
    //   legalProjectFactsData.project.description,
    //   legalProjectFactsData.userRelatedFeatures.contractsConcludedOnWebsite,
    //   "BFSG primarily concerns covered products/services, especially consumer-facing electronic commerce and comparable covered services; the modeled site is an informational archive/portfolio without direct online contracting."
    // ]
    accessibilityStatement: false,
  },
};
